### ISSUE TITLE
data file 

### ISSUE THREAD

**Issue by RuiRao** [nandahkrishna/StockTrading#1]
hello,author ,thank you for your codes, but now I have a serious problem,the files you supplied didn't include the data file .I would appreciate it if you could upload the data file.

**Comment by nandahkrishna** [comment]
I've added a link to the dataset and mentioned the specific file, `aapl.us.txt`, in the README.

We used Apple's stock market data from the [Huge Stock Market Dataset](https://www.kaggle.com/borismarjanovic/price-volume-data-for-all-us-stocks-etfs?) on Kaggle. You can find the file in the `Stocks` subdirectory there. Unfortunately I don't think I can upload the data file here, to avoid violating any Copyright restrictions.

Thanks!
